--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 25 2015 12:40
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'Telefon'   
--
DROP TABLE Telefon
GO
--
-- Drop Table    : 'bor'   
--
DROP TABLE bor
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
--
-- Drop Table    : 'Adresse'   
--
DROP TABLE Adresse
GO
