--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 25 2015 12:40
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Adresse'   
-- AdresseID       :  
-- Type            :  
-- VejNavn         :  
-- HusNummer       :  
-- PostNummer      :  
-- City            :  
--
CREATE TABLE Adresse (
    AdresseID      BIGINT NOT NULL IDENTITY,
    Type           NVARCHAR(MAX) NOT NULL,
    VejNavn        NVARCHAR(MAX) NOT NULL,
    HusNummer      BIGINT NOT NULL,
    PostNummer     BIGINT NOT NULL,
    City           NVARCHAR NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseID))
GO

--
-- Create Table    : 'Person'   
-- PersonID        :  
-- CPRNr           :  
-- Fornavn         :  
-- Mellemnavn      :  
-- Efternavn       :  
-- type            :  
-- AdresseID       :  (references Adresse.AdresseID)
--
CREATE TABLE Person (
    PersonID       BIGINT NOT NULL IDENTITY,
    CPRNr          BIGINT NOT NULL,
    Fornavn        NVARCHAR(MAX) NOT NULL,
    Mellemnavn     NVARCHAR(MAX) NULL,
    Efternavn      NVARCHAR(MAX) NOT NULL,
    type           NVARCHAR(MAX) NOT NULL,
    AdresseID      BIGINT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID),
CONSTRAINT fk_Person FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'bor'   
-- PersonID        :  (references Person.PersonID)
-- AdresseID       :  (references Adresse.AdresseID)
--
CREATE TABLE bor (
    PersonID       BIGINT NOT NULL,
    AdresseID      BIGINT NOT NULL,
CONSTRAINT pk_bor PRIMARY KEY CLUSTERED (PersonID,AdresseID),
CONSTRAINT fk_bor FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_bor2 FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO

--
-- Create Table    : 'Telefon'   
-- TelefonID       :  
-- PersonID        :  (references Person.PersonID)
-- TelefonNr       :  
-- Type            :  
--
CREATE TABLE Telefon (
    TelefonID      BIGINT NOT NULL IDENTITY,
    PersonID       BIGINT NOT NULL,
    TelefonNr      BIGINT NOT NULL,
    Type           NVARCHAR(MAX) NOT NULL,
CONSTRAINT pk_Telefon PRIMARY KEY CLUSTERED (TelefonID),
CONSTRAINT fk_Telefon FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO



